Update mylib.py
I keep getting this error! Does anyone know what it means?

Traceback (most recent call last):
  File "dakbaba-4.1.py", line 27, in <module>
    mylog.debug('will log if priority is DEBUG only')
  File "/Users/deryaakbaba-locus/Python/mylib.py", line 20, in debug
    self.write_log(msg, 1)
  File "/Users/deryaakbaba-locus/Python/mylib.py", line 48, in write_log
    self.compose_prepend()
  File "/Users/deryaakbaba-locus/Python/mylib.py", line 61, in compose_prepend
    fh.writelines(time_date)
TypeError: 'str' does not support the buffer interface